# Generated by Django 4.2.7 on 2025-11-08 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Her Beauty Hub', max_length=200)),
                ('tagline', models.CharField(default='Glow. Style. Confidence.', max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number with country code', max_length=20)),
                ('weekday_hours', models.CharField(default='9:00 AM - 7:00 PM', max_length=100)),
                ('saturday_hours', models.CharField(default='10:00 AM - 8:00 PM', max_length=100)),
                ('sunday_hours', models.CharField(default='12:00 PM - 6:00 PM', max_length=100)),
                ('about_text', models.TextField(help_text='About the business')),
                ('mission', models.TextField(help_text='Mission statement')),
                ('vision', models.TextField(help_text='Vision statement')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Message subject', max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Currency code (e.g., USD, EUR, NGN)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €, ₦)', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate relative to base currency', max_digits=10)),
                ('is_base', models.BooleanField(default=False, help_text='Is this the base currency?')),
                ('active', models.BooleanField(default=True, help_text='Is currency active?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DailyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title', max_length=200)),
                ('description', models.TextField(help_text='Offer details')),
                ('image', models.ImageField(help_text='Offer image', upload_to='offers/')),
                ('discount_percentage', models.IntegerField(help_text='Discount percentage (e.g., 20 for 20% off)', validators=[django.core.validators.MinValueValidator(1)])),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (auto-calculated)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(help_text='Offer start date')),
                ('end_date', models.DateField(help_text='Offer end date')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions')),
                ('active', models.BooleanField(default=True, help_text='Is offer active?')),
                ('featured', models.BooleanField(default=False, help_text='Feature prominently?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Offer',
                'verbose_name_plural': 'Daily Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title or caption', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or details')),
                ('image', models.ImageField(help_text='Gallery image', upload_to='gallery/')),
                ('category', models.CharField(blank=True, help_text="Category (e.g., 'Hair', 'Makeup', 'Fashion')", max_length=100)),
                ('featured', models.BooleanField(default=False, help_text='Display prominently?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fashion', 'Fashion & Clothing'), ('perfume', 'Perfumes & Fragrances'), ('beauty', 'Beauty Products'), ('accessories', 'Accessories')], default='fashion', max_length=50)),
                ('image', models.ImageField(help_text='Product image', upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in base currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Price in EUR (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_gbp', models.DecimalField(blank=True, decimal_places=2, help_text='Price in GBP (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Quantity in stock')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Low stock alert threshold')),
                ('available', models.BooleanField(default=True, help_text='In stock?')),
                ('featured', models.BooleanField(default=False, help_text='Display on home page?')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Product weight (kg)', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Hair Styling)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('image', models.ImageField(blank=True, help_text='Service image (optional)', null=True, upload_to='services/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price (optional, e.g., 30.00)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.CharField(blank=True, help_text="Service duration (e.g., '1-2 hours')", max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-cut')", max_length=100)),
                ('featured', models.BooleanField(default=False, help_text='Display on home page?')),
                ('active', models.BooleanField(default=True, help_text='Is this service currently available?')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('pinterest', 'Pinterest')], max_length=50)),
                ('url', models.URLField(help_text='Full URL to your profile')),
                ('username', models.CharField(blank=True, help_text='Your username (optional)', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('description', models.TextField(help_text='Video description')),
                ('video_file', models.FileField(help_text='Upload video file (MP4, MOV, AVI, WEBM)', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('thumbnail', models.ImageField(help_text='Video thumbnail/preview image', upload_to='video_thumbnails/')),
                ('category', models.CharField(choices=[('tutorial', 'Tutorial'), ('transformation', 'Transformation'), ('promotion', 'Promotion'), ('testimonial', 'Video Testimonial'), ('behind_scenes', 'Behind the Scenes')], default='promotion', max_length=50)),
                ('duration', models.CharField(blank=True, help_text="Video duration (e.g., '2:30')", max_length=20)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('featured', models.BooleanField(default=False, help_text='Feature on home page?')),
                ('active', models.BooleanField(default=True, help_text='Is video active?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_initial', models.CharField(blank=True, help_text='First letter of name (for avatar)', max_length=1)),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5', validators=[django.core.validators.MinValueValidator(1)])),
                ('testimonial', models.TextField(help_text='Customer review')),
                ('approved', models.BooleanField(default=False, help_text='Show on website?')),
                ('featured', models.BooleanField(default=False, help_text='Display on home page?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='beautyhub.service')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(help_text='Rating 1-5', validators=[django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField(help_text='Review text')),
                ('approved', models.BooleanField(default=False, help_text='Approved for display?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beautyhub.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name", max_length=200)),
                ('email', models.EmailField(help_text="Client's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('date', models.DateField(help_text='Preferred appointment date')),
                ('time', models.TimeField(blank=True, help_text='Preferred appointment time', null=True)),
                ('message', models.TextField(blank=True, help_text='Additional notes or requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='Service to book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='beautyhub.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
