# Generated by Django 4.2.7 on 2025-11-08 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='clothing/')),
                ('category', models.CharField(choices=[('dress', 'Dress'), ('top', 'Top'), ('bottom', 'Bottom'), ('outfit', 'Complete Outfit'), ('accessory', 'Accessory')], max_length=50)),
                ('available_sizes', models.CharField(help_text='Available sizes (e.g., S, M, L)', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clothing Item',
                'verbose_name_plural': 'Clothing Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HairStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hairstyles/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.CharField(help_text='Estimated duration', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('complex', 'Complex')], default='medium', max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hair Style',
                'verbose_name_plural': 'Hair Styles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('product_type', models.CharField(help_text='Hairstyle, Perfume, Clothing', max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Message',
                'verbose_name_plural': 'Order Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='perfumes/')),
                ('scent_type', models.CharField(choices=[('floral', 'Floral'), ('fruity', 'Fruity'), ('oriental', 'Oriental'), ('woody', 'Woody'), ('fresh', 'Fresh')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.CharField(help_text='e.g., 50ml, 100ml', max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfume',
                'verbose_name_plural': 'Perfumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
