# Generated by Django 4.2.7 on 2025-11-08 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyhub', '0002_clothingitem_hairstyle_ordermessage_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='price_ksh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in Kenyan Shillings (KSH)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration in minutes (e.g., 120 for 2 hours)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='price_ksh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in Kenyan Shillings (KSH)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='product_price_ksh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in KSH', max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='total_amount_ksh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total in KSH', max_digits=10),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price_ksh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in Kenyan Shillings (KSH)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='duration',
            field=models.CharField(help_text="Display text (e.g., '2-3 hours')", max_length=100),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hairstyles/'),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
