# Generated by Django 4.2.7 on 2025-11-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyhub', '0003_clothingitem_price_ksh_clothingitem_price_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional perfume photo', upload_to='perfumes/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='beautyhub.perfume')),
            ],
            options={
                'verbose_name': 'Perfume Image',
                'verbose_name_plural': 'Perfume Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HairStyleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional hairstyle photo', upload_to='hairstyles/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='beautyhub.hairstyle')),
            ],
            options={
                'verbose_name': 'Hairstyle Image',
                'verbose_name_plural': 'Hairstyle Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional clothing photo', upload_to='clothing/gallery/')),
                ('caption', models.CharField(blank=True, help_text="Optional image caption (e.g., 'Back view', 'Detail shot')", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='beautyhub.clothingitem')),
            ],
            options={
                'verbose_name': 'Clothing Image',
                'verbose_name_plural': 'Clothing Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
