# Generated by Django 4.2.7 on 2025-11-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beautyhub', '0004_perfumeimage_hairstyleimage_clothingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('birthday', models.DateField(blank=True, help_text='Birthday for special month discounts!', null=True)),
                ('is_student', models.BooleanField(default=False, help_text='Verified student status')),
                ('student_id', models.CharField(blank=True, help_text='Student ID number for verification', max_length=50)),
                ('university', models.CharField(blank=True, help_text='University/College name', max_length=200)),
                ('student_verified_date', models.DateTimeField(blank=True, help_text='When student status was verified', null=True)),
                ('loyalty_points', models.IntegerField(default=0, help_text='Earn 10 points per KSH 100 spent!')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Lifetime points earned')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent (KSH)', max_digits=10)),
                ('referral_code', models.CharField(blank=True, help_text='Unique referral code (auto-generated)', max_length=10, unique=True)),
                ('referral_count', models.IntegerField(default=0, help_text='Number of friends referred')),
                ('vip_status', models.BooleanField(default=False, help_text='VIP customer (5+ orders or 1000+ points)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='Who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='beautyhub.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(help_text='Referral code that was used', max_length=10)),
                ('reward_claimed', models.BooleanField(default=False, help_text='Has referrer claimed reward?')),
                ('reward_type', models.CharField(blank=True, help_text="Type of reward (e.g., '100 points', 'Free service')", max_length=50)),
                ('referred_user_made_purchase', models.BooleanField(default=False, help_text='Has referred user made their first purchase?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(help_text='User who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_relation', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who referred', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('original_price_ksh', models.DecimalField(decimal_places=2, help_text='Original price before discounts', max_digits=10)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Total discount applied (%)')),
                ('discount_amount_ksh', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in KSH', max_digits=10)),
                ('final_amount_ksh', models.DecimalField(decimal_places=2, help_text='Final amount paid', max_digits=10)),
                ('points_earned', models.IntegerField(default=0, help_text='Loyalty points earned from this order')),
                ('points_redeemed', models.IntegerField(default=0, help_text='Loyalty points used for discount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Registered user (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('clothing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyhub.clothingitem')),
                ('hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyhub.hairstyle')),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyhub.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'unique_together': {('user', 'clothing'), ('user', 'perfume'), ('user', 'hairstyle')},
            },
        ),
    ]
