# Generated by Django 4.2.7 on 2025-11-09 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beautyhub', '0005_userprofile_referral_order_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name for guest comments', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email for guest comments', max_length=254)),
                ('comment', models.TextField(help_text='Comment text')),
                ('approved', models.BooleanField(default=True, help_text='Approve before showing publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='beautyhub.galleryitem')),
                ('user', models.ForeignKey(blank=True, help_text='User who commented (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Comment',
                'verbose_name_plural': 'Gallery Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for guest likes', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='beautyhub.galleryitem')),
                ('user', models.ForeignKey(blank=True, help_text='User who liked (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Like',
                'verbose_name_plural': 'Gallery Likes',
                'unique_together': {('gallery_item', 'user'), ('gallery_item', 'session_id')},
            },
        ),
    ]
